// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmtUQ24y-AhOjd7rG8ubmW841RQvw0QM',
    appId: '1:60383437942:web:78d4a53fed23fce26e2b57',
    messagingSenderId: '60383437942',
    projectId: 'photo-journal-synoptic',
    authDomain: 'photo-journal-synoptic.firebaseapp.com',
    storageBucket: 'photo-journal-synoptic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY7nFwTU-TeVoidVlfkAVD5SDwFor6l_g',
    appId: '1:60383437942:android:003e8cbb8c77f4f96e2b57',
    messagingSenderId: '60383437942',
    projectId: 'photo-journal-synoptic',
    storageBucket: 'photo-journal-synoptic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJw60Lq-MDNjJmd7fkLGpi1NfW1GFR7I0',
    appId: '1:60383437942:ios:f4bbaf5751f5030c6e2b57',
    messagingSenderId: '60383437942',
    projectId: 'photo-journal-synoptic',
    storageBucket: 'photo-journal-synoptic.firebasestorage.app',
    iosBundleId: 'com.example.photoJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJw60Lq-MDNjJmd7fkLGpi1NfW1GFR7I0',
    appId: '1:60383437942:ios:f4bbaf5751f5030c6e2b57',
    messagingSenderId: '60383437942',
    projectId: 'photo-journal-synoptic',
    storageBucket: 'photo-journal-synoptic.firebasestorage.app',
    iosBundleId: 'com.example.photoJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFmtUQ24y-AhOjd7rG8ubmW841RQvw0QM',
    appId: '1:60383437942:web:91f5da11d8112f6b6e2b57',
    messagingSenderId: '60383437942',
    projectId: 'photo-journal-synoptic',
    authDomain: 'photo-journal-synoptic.firebaseapp.com',
    storageBucket: 'photo-journal-synoptic.firebasestorage.app',
  );
}
